### ISSUE TITLE
Wiki is down

### ISSUE THREAD

**Issue by Cysioland** [inspircd/wiki#29]
When I try to browse it, it's stuck connecting, and then timeouts.

**Comment by SaberUK** [comment]
The ChatSpike server is broken. Use web.archive.org for now.

**Comment by braindigitalis** [comment]
The server is back up, the tunnel/proxy which allows access was having issues.

**Comment by Adam-** [comment]
@braindigitalis it's down again.

**Comment by eadmund** [comment]
The site has an incorrect SSL certificate.

**Comment by braindigitalis** [comment]
The server has been moved and I am still migrating sites. It should be back up Tuesday.

Craig Edwards 
Brainbox.cc

---- Bob Uhl wrote ----

**Comment by SaberUK** [comment]
Fixed.
