### ISSUE TITLE
Running in isolation

### ISSUE THREAD

**Issue by timothystone** [inspircd/wiki#30]
I would like to see a page (or sidebars within the existing documentation) that highlights how I might run `inspircd` in isolation. By isolation, the context is more about a corporate communication platform that does not connect to the wider IRC nets "in the wild" or participate as such. I might have `inspircd` running on multiple datacenters that might talk to each other to support load, etc., but they would never talk to the outside or wider/global IRC community.

While it might be solved by network configurations or other isolation techniques, what I'm really thinking about is an `inspircd` that is **properly configured** so as not to attempt external connection. So that there's no unexpected networking attempts. An `inspircd` server that is happy being a loner.

Even if this just a blurb regarding the use or un-use of the spanning tree module (?). I think that's the module that basically allows `inspircd` to join and register with these networks.

**Comment by attilamolnar** [comment]
Hello,

InspIRCd runs in isolation by default, it doesn't connect to any other server unless configured to do so. All server to server connections are configured manually, by specifying the remote address, credentials, etc.

**Comment by timothystone** [comment]
Thanks! i've been playing with it since posting.
